GET http://localhost:4200/api/user/1/media HTTP/1.1

###

POST http://localhost:XXXX/ HTTP/1.1
content-type: application/json

{
  "title": "Stalker"
}

###
POST http://localhost:4200/api/register HTTP/1.1
content-type: application/json

{
    "email": "blibl.blibli@email.com",
    "username": "bli",
    "password": "aaaa",
    "firstName": "bli",
    "lastName": "bli"
}

###
GET http://localhost:4200/api/register HTTP/1.1

